version: "3.2"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    network_mode: host
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: agoda123*

