package com.agoda.rolladillo

import java.io.InputStream
import java.io.Reader
import java.math.BigDecimal
import java.net.URL
import java.sql.*
import java.sql.Date
import java.util.*

class ProxyCallableStatement(val callableStatement: CallableStatement) : CallableStatement {
    override fun <T : Any?> unwrap(iface: Class<T>?): T {
        TODO("Not yet implemented")
    }

    override fun isWrapperFor(iface: Class<*>?): Boolean {
        TODO("Not yet implemented")
    }

    override fun close() {
        TODO("Not yet implemented")
    }

    override fun executeQuery(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun executeQuery(sql: String?): ResultSet {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int {
        TODO("Not yet implemented")
    }

    override fun getMaxFieldSize(): Int {
        TODO("Not yet implemented")
    }

    override fun setMaxFieldSize(max: Int) {
        TODO("Not yet implemented")
    }

    override fun getMaxRows(): Int {
        TODO("Not yet implemented")
    }

    override fun setMaxRows(max: Int) {
        TODO("Not yet implemented")
    }

    override fun setEscapeProcessing(enable: Boolean) {
        TODO("Not yet implemented")
    }

    override fun getQueryTimeout(): Int {
        TODO("Not yet implemented")
    }

    override fun setQueryTimeout(seconds: Int) {
        TODO("Not yet implemented")
    }

    override fun cancel() {
        TODO("Not yet implemented")
    }

    override fun getWarnings(): SQLWarning {
        TODO("Not yet implemented")
    }

    override fun clearWarnings() {
        TODO("Not yet implemented")
    }

    override fun setCursorName(name: String?) {
        TODO("Not yet implemented")
    }

    override fun execute(): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean {
        TODO("Not yet implemented")
    }

    override fun getResultSet(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun getUpdateCount(): Int {
        TODO("Not yet implemented")
    }

    override fun getMoreResults(): Boolean {
        TODO("Not yet implemented")
    }

    override fun getMoreResults(current: Int): Boolean {
        TODO("Not yet implemented")
    }

    override fun setFetchDirection(direction: Int) {
        TODO("Not yet implemented")
    }

    override fun getFetchDirection(): Int {
        TODO("Not yet implemented")
    }

    override fun setFetchSize(rows: Int) {
        TODO("Not yet implemented")
    }

    override fun getFetchSize(): Int {
        TODO("Not yet implemented")
    }

    override fun getResultSetConcurrency(): Int {
        TODO("Not yet implemented")
    }

    override fun getResultSetType(): Int {
        TODO("Not yet implemented")
    }

    override fun addBatch() {
        TODO("Not yet implemented")
    }

    override fun addBatch(sql: String?) {
        TODO("Not yet implemented")
    }

    override fun clearBatch() {
        TODO("Not yet implemented")
    }

    override fun executeBatch(): IntArray {
        TODO("Not yet implemented")
    }

    override fun getConnection(): Connection {
        TODO("Not yet implemented")
    }

    override fun getGeneratedKeys(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun getResultSetHoldability(): Int {
        TODO("Not yet implemented")
    }

    override fun isClosed(): Boolean {
        TODO("Not yet implemented")
    }

    override fun setPoolable(poolable: Boolean) {
        TODO("Not yet implemented")
    }

    override fun isPoolable(): Boolean {
        TODO("Not yet implemented")
    }

    override fun closeOnCompletion() {
        TODO("Not yet implemented")
    }

    override fun isCloseOnCompletion(): Boolean {
        TODO("Not yet implemented")
    }

    override fun setNull(parameterName: String?, sqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun setNull(parameterName: String?, sqlType: Int, typeName: String?) {
        TODO("Not yet implemented")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int, typeName: String?) {
        TODO("Not yet implemented")
    }

    override fun setBoolean(parameterName: String?, x: Boolean) {
        TODO("Not yet implemented")
    }

    override fun setBoolean(parameterIndex: Int, x: Boolean) {
        TODO("Not yet implemented")
    }

    override fun setByte(parameterName: String?, x: Byte) {
        TODO("Not yet implemented")
    }

    override fun setByte(parameterIndex: Int, x: Byte) {
        TODO("Not yet implemented")
    }

    override fun setShort(parameterName: String?, x: Short) {
        TODO("Not yet implemented")
    }

    override fun setShort(parameterIndex: Int, x: Short) {
        TODO("Not yet implemented")
    }

    override fun setInt(parameterName: String?, x: Int) {
        TODO("Not yet implemented")
    }

    override fun setInt(parameterIndex: Int, x: Int) {
        TODO("Not yet implemented")
    }

    override fun setLong(parameterName: String?, x: Long) {
        TODO("Not yet implemented")
    }

    override fun setLong(parameterIndex: Int, x: Long) {
        TODO("Not yet implemented")
    }

    override fun setFloat(parameterName: String?, x: Float) {
        TODO("Not yet implemented")
    }

    override fun setFloat(parameterIndex: Int, x: Float) {
        TODO("Not yet implemented")
    }

    override fun setDouble(parameterName: String?, x: Double) {
        TODO("Not yet implemented")
    }

    override fun setDouble(parameterIndex: Int, x: Double) {
        TODO("Not yet implemented")
    }

    override fun setBigDecimal(parameterName: String?, x: BigDecimal?) {
        TODO("Not yet implemented")
    }

    override fun setBigDecimal(parameterIndex: Int, x: BigDecimal?) {
        TODO("Not yet implemented")
    }

    override fun setString(parameterName: String?, x: String?) {
        TODO("Not yet implemented")
    }

    override fun setString(parameterIndex: Int, x: String?) {
        TODO("Not yet implemented")
    }

    override fun setBytes(parameterName: String?, x: ByteArray?) {
        TODO("Not yet implemented")
    }

    override fun setBytes(parameterIndex: Int, x: ByteArray?) {
        TODO("Not yet implemented")
    }

    override fun setDate(parameterName: String?, x: Date?) {
        TODO("Not yet implemented")
    }

    override fun setDate(parameterName: String?, x: Date?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setDate(parameterIndex: Int, x: Date?) {
        TODO("Not yet implemented")
    }

    override fun setDate(parameterIndex: Int, x: Date?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setTime(parameterName: String?, x: Time?) {
        TODO("Not yet implemented")
    }

    override fun setTime(parameterName: String?, x: Time?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setTime(parameterIndex: Int, x: Time?) {
        TODO("Not yet implemented")
    }

    override fun setTime(parameterIndex: Int, x: Time?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setTimestamp(parameterName: String?, x: Timestamp?) {
        TODO("Not yet implemented")
    }

    override fun setTimestamp(parameterName: String?, x: Timestamp?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?) {
        TODO("Not yet implemented")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?, cal: Calendar?) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterName: String?, x: InputStream?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterName: String?, x: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterName: String?, x: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun setUnicodeStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterName: String?, x: InputStream?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterName: String?, x: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterName: String?, x: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun clearParameters() {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterName: String?, x: Any?, targetSqlType: Int, scale: Int) {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterName: String?, x: Any?, targetSqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterName: String?, x: Any?) {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?) {
        TODO("Not yet implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int, scaleOrLength: Int) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterName: String?, reader: Reader?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterName: String?, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterName: String?, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Int) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setRef(parameterIndex: Int, x: Ref?) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterName: String?, inputStream: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterName: String?, x: Blob?) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterName: String?, inputStream: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterIndex: Int, x: Blob?) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterName: String?, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterName: String?, x: Clob?) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterName: String?, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterIndex: Int, x: Clob?) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setArray(parameterIndex: Int, x: java.sql.Array?) {
        TODO("Not yet implemented")
    }

    override fun getMetaData(): ResultSetMetaData {
        TODO("Not yet implemented")
    }

    override fun setURL(parameterName: String?, `val`: URL?) {
        TODO("Not yet implemented")
    }

    override fun setURL(parameterIndex: Int, x: URL?) {
        TODO("Not yet implemented")
    }

    override fun getParameterMetaData(): ParameterMetaData {
        TODO("Not yet implemented")
    }

    override fun setRowId(parameterName: String?, x: RowId?) {
        TODO("Not yet implemented")
    }

    override fun setRowId(parameterIndex: Int, x: RowId?) {
        TODO("Not yet implemented")
    }

    override fun setNString(parameterName: String?, value: String?) {
        TODO("Not yet implemented")
    }

    override fun setNString(parameterIndex: Int, value: String?) {
        TODO("Not yet implemented")
    }

    override fun setNCharacterStream(parameterName: String?, value: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setNCharacterStream(parameterName: String?, value: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterName: String?, value: NClob?) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterName: String?, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterName: String?, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterIndex: Int, value: NClob?) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("Not yet implemented")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?) {
        TODO("Not yet implemented")
    }

    override fun setSQLXML(parameterName: String?, xmlObject: SQLXML?) {
        TODO("Not yet implemented")
    }

    override fun setSQLXML(parameterIndex: Int, xmlObject: SQLXML?) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterIndex: Int, sqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterIndex: Int, sqlType: Int, scale: Int) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterIndex: Int, sqlType: Int, typeName: String?) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterName: String?, sqlType: Int) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterName: String?, sqlType: Int, scale: Int) {
        TODO("Not yet implemented")
    }

    override fun registerOutParameter(parameterName: String?, sqlType: Int, typeName: String?) {
        TODO("Not yet implemented")
    }

    override fun wasNull(): Boolean {
        TODO("Not yet implemented")
    }

    override fun getString(parameterIndex: Int): String {
        TODO("Not yet implemented")
    }

    override fun getString(parameterName: String?): String {
        TODO("Not yet implemented")
    }

    override fun getBoolean(parameterIndex: Int): Boolean {
        TODO("Not yet implemented")
    }

    override fun getBoolean(parameterName: String?): Boolean {
        TODO("Not yet implemented")
    }

    override fun getByte(parameterIndex: Int): Byte {
        TODO("Not yet implemented")
    }

    override fun getByte(parameterName: String?): Byte {
        TODO("Not yet implemented")
    }

    override fun getShort(parameterIndex: Int): Short {
        TODO("Not yet implemented")
    }

    override fun getShort(parameterName: String?): Short {
        TODO("Not yet implemented")
    }

    override fun getInt(parameterIndex: Int): Int {
        TODO("Not yet implemented")
    }

    override fun getInt(parameterName: String?): Int {
        TODO("Not yet implemented")
    }

    override fun getLong(parameterIndex: Int): Long {
        TODO("Not yet implemented")
    }

    override fun getLong(parameterName: String?): Long {
        TODO("Not yet implemented")
    }

    override fun getFloat(parameterIndex: Int): Float {
        TODO("Not yet implemented")
    }

    override fun getFloat(parameterName: String?): Float {
        TODO("Not yet implemented")
    }

    override fun getDouble(parameterIndex: Int): Double {
        TODO("Not yet implemented")
    }

    override fun getDouble(parameterName: String?): Double {
        TODO("Not yet implemented")
    }

    override fun getBigDecimal(parameterIndex: Int, scale: Int): BigDecimal {
        TODO("Not yet implemented")
    }

    override fun getBigDecimal(parameterIndex: Int): BigDecimal {
        TODO("Not yet implemented")
    }

    override fun getBigDecimal(parameterName: String?): BigDecimal {
        TODO("Not yet implemented")
    }

    override fun getBytes(parameterIndex: Int): ByteArray {
        TODO("Not yet implemented")
    }

    override fun getBytes(parameterName: String?): ByteArray {
        TODO("Not yet implemented")
    }

    override fun getDate(parameterIndex: Int): Date {
        TODO("Not yet implemented")
    }

    override fun getDate(parameterIndex: Int, cal: Calendar?): Date {
        TODO("Not yet implemented")
    }

    override fun getDate(parameterName: String?): Date {
        TODO("Not yet implemented")
    }

    override fun getDate(parameterName: String?, cal: Calendar?): Date {
        TODO("Not yet implemented")
    }

    override fun getTime(parameterIndex: Int): Time {
        TODO("Not yet implemented")
    }

    override fun getTime(parameterIndex: Int, cal: Calendar?): Time {
        TODO("Not yet implemented")
    }

    override fun getTime(parameterName: String?): Time {
        TODO("Not yet implemented")
    }

    override fun getTime(parameterName: String?, cal: Calendar?): Time {
        TODO("Not yet implemented")
    }

    override fun getTimestamp(parameterIndex: Int): Timestamp {
        TODO("Not yet implemented")
    }

    override fun getTimestamp(parameterIndex: Int, cal: Calendar?): Timestamp {
        TODO("Not yet implemented")
    }

    override fun getTimestamp(parameterName: String?): Timestamp {
        TODO("Not yet implemented")
    }

    override fun getTimestamp(parameterName: String?, cal: Calendar?): Timestamp {
        TODO("Not yet implemented")
    }

    override fun getObject(parameterIndex: Int): Any {
        TODO("Not yet implemented")
    }

    override fun getObject(parameterIndex: Int, map: MutableMap<String, Class<*>>?): Any {
        TODO("Not yet implemented")
    }

    override fun getObject(parameterName: String?): Any {
        TODO("Not yet implemented")
    }

    override fun getObject(parameterName: String?, map: MutableMap<String, Class<*>>?): Any {
        TODO("Not yet implemented")
    }

    override fun <T : Any?> getObject(parameterIndex: Int, type: Class<T>?): T {
        TODO("Not yet implemented")
    }

    override fun <T : Any?> getObject(parameterName: String?, type: Class<T>?): T {
        TODO("Not yet implemented")
    }

    override fun getRef(parameterIndex: Int): Ref {
        TODO("Not yet implemented")
    }

    override fun getRef(parameterName: String?): Ref {
        TODO("Not yet implemented")
    }

    override fun getBlob(parameterIndex: Int): Blob {
        TODO("Not yet implemented")
    }

    override fun getBlob(parameterName: String?): Blob {
        TODO("Not yet implemented")
    }

    override fun getClob(parameterIndex: Int): Clob {
        TODO("Not yet implemented")
    }

    override fun getClob(parameterName: String?): Clob {
        TODO("Not yet implemented")
    }

    override fun getArray(parameterIndex: Int): java.sql.Array {
        TODO("Not yet implemented")
    }

    override fun getArray(parameterName: String?): java.sql.Array {
        TODO("Not yet implemented")
    }

    override fun getURL(parameterIndex: Int): URL {
        TODO("Not yet implemented")
    }

    override fun getURL(parameterName: String?): URL {
        TODO("Not yet implemented")
    }

    override fun getRowId(parameterIndex: Int): RowId {
        TODO("Not yet implemented")
    }

    override fun getRowId(parameterName: String?): RowId {
        TODO("Not yet implemented")
    }

    override fun getNClob(parameterIndex: Int): NClob {
        TODO("Not yet implemented")
    }

    override fun getNClob(parameterName: String?): NClob {
        TODO("Not yet implemented")
    }

    override fun getSQLXML(parameterIndex: Int): SQLXML {
        TODO("Not yet implemented")
    }

    override fun getSQLXML(parameterName: String?): SQLXML {
        TODO("Not yet implemented")
    }

    override fun getNString(parameterIndex: Int): String {
        TODO("Not yet implemented")
    }

    override fun getNString(parameterName: String?): String {
        TODO("Not yet implemented")
    }

    override fun getNCharacterStream(parameterIndex: Int): Reader {
        TODO("Not yet implemented")
    }

    override fun getNCharacterStream(parameterName: String?): Reader {
        TODO("Not yet implemented")
    }

    override fun getCharacterStream(parameterIndex: Int): Reader {
        TODO("Not yet implemented")
    }

    override fun getCharacterStream(parameterName: String?): Reader {
        TODO("Not yet implemented")
    }

}